version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: trello
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod

volumes:
  pgdata:
