version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_PASSWORD: root123
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/trello
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: root123

    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    container_name: springboot-app
    depends_on:
      - db
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

volumes:
  pgdata:

networks:
  app-network:
    driver: bridge
