name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kodingiz
        uses: actions/checkout@v3

      - name: Serverga ulanib projectni yangilash
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.SERVER_USER }}/YOUR_REPO_NAME
            git pull origin main
            docker-compose down
            docker-compose up --build -d
